start: "appId:" SP STRING NL SEP NL steps
SEP: "---"  
steps: step (step)* (NL)?
step: "-" SP command NL?
command: "launchApp" | "back" | "hideKeyboard" | "waitForAnimationToEnd" | "clearState" | "clearKeychain" | "takeScreenshot" | "tapOn:" SP STRING | "inputText:" SP STRING | "assertVisible:" SP STRING | "assertNotVisible:" SP STRING | "openLink:" SP STRING | tap_on_map | press_key_map | erase_text_map | scroll_map | swipe_map | take_screenshot_map | run_flow_map | run_script_map
tap_on_map: "tapOn:" NL SP2 selector_kv
selector_kv: "id:" SP STRING | "text:" SP STRING
press_key_map: "pressKey:" NL SP2 "key:" SP KEY
erase_text_map: "eraseText:" NL SP2 "characters:" SP INT
scroll_map: "scroll:" NL SP2 "direction:" SP DIRECTION
swipe_map: "swipe:" NL SP2 "direction:" SP DIRECTION
take_screenshot_map: "takeScreenshot:" NL SP2 "name:" SP STRING
run_flow_map: "runFlow:" NL SP2 "file:" SP PATH
run_script_map: "runScript:" NL SP2 "file:" SP PATH
condition_kv: "visible:" SP STRING
            | "notVisible:" SP STRING
            | "platform:" SP PLATFORM
            | "true:" SP STRING
SP: " "
SP2: "  "
SP4: "    "
NL: /\r?\n/
STRING: /"[^"\n]{1,200}"/
PATH: STRING
INT: /[0-9]{1,6}/
BOOL: "true" | "false"
DIRECTION: "up" | "down" | "left" | "right"
KEY: "enter" | "return" | "go" | "done" | "tab" | "escape" | "space" | "backspace" | "delete" | "back" | "home" | "menu" | "search" | "volumeUp" | "volumeDown" | "camera" | "up" | "down" | "left" | "right"
PLATFORM: "iOS" | "Android"
